name: Build & Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/build.template.yml
