<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>This package provides an extension to Nexplore.Practices.CommandLine for executing EF DB migrations in your custom CLI.</Description>
        <PackageTags>Nexplore.Practices Practices CommandLine CLI Database Migrate</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Nexplore.Practices.CommandLine\Nexplore.Practices.CommandLine.csproj" />
    </ItemGroup>

</Project>
