//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexplore.Practices.Tests.Unit.Web.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexplore.Practices.Tests.Unit.Web.Localization.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {0}.
        /// </summary>
        internal static string CompositeFormat {
            get {
                return ResourceManager.GetString("CompositeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {0:00.0}.
        /// </summary>
        internal static string CompositeFormatWithFloatFormatter {
            get {
                return ResourceManager.GetString("CompositeFormatWithFloatFormatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {0} {1}.
        /// </summary>
        internal static string CompositeFormatWithTwoIndicies {
            get {
                return ResourceManager.GetString("CompositeFormatWithTwoIndicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception from TestResource.
        /// </summary>
        internal static string Exceptions_UnhandledException {
            get {
                return ResourceManager.GetString("Exceptions_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore
        ///et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
        ///Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,
        ///consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,
        ///sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongFormatExpected {
            get {
                return ResourceManager.GetString("LongFormatExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum {{ dolor }} sit {0}, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore
        ///et {{ dolor }}e magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo {{ dolor }}es et ea rebum.
        ///Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum {{ dolor }} sit {0}. Lorem ipsum {{ dolor }} sit {0},
        ///consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et {{ dolor }}e magna aliquyam erat,
        ///sed diam voluptua. At vero eos et accusam  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongMixedFormat {
            get {
                return ResourceManager.GetString("LongMixedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {0} {{ bar }} {1}.
        /// </summary>
        internal static string MixedFormat {
            get {
                return ResourceManager.GetString("MixedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {0} {{ bar }} {2}.
        /// </summary>
        internal static string MixedFormat2 {
            get {
                return ResourceManager.GetString("MixedFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {{ bar }}.
        /// </summary>
        internal static string TemplateFormat {
            get {
                return ResourceManager.GetString("TemplateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {{ baz{{ bar }} }}.
        /// </summary>
        internal static string TemplateFormatWithNestedTemplateFormat {
            get {
                return ResourceManager.GetString("TemplateFormatWithNestedTemplateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {{bar}}.
        /// </summary>
        internal static string TemplateFormatWithoutSpaces {
            get {
                return ResourceManager.GetString("TemplateFormatWithoutSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {{ bar }}{{ bar }}.
        /// </summary>
        internal static string TemplateFormatWithRecurrence {
            get {
                return ResourceManager.GetString("TemplateFormatWithRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {{ bar }} {{ baz }}.
        /// </summary>
        internal static string TemplateFormatWithTwoKeys {
            get {
                return ResourceManager.GetString("TemplateFormatWithTwoKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foo {{                                     bar}}.
        /// </summary>
        internal static string TemplateFormatWithUnevenSpaces {
            get {
                return ResourceManager.GetString("TemplateFormatWithUnevenSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: Text available in both files.
        /// </summary>
        internal static string Testfallback_Both {
            get {
                return ResourceManager.GetString("Testfallback_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: Text available only in test.
        /// </summary>
        internal static string Testfallback_OnlyInTest {
            get {
                return ResourceManager.GetString("Testfallback_OnlyInTest", resourceCulture);
            }
        }
    }
}
