<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>This package provides a powerful IoC enabling api for System.CommandLine.</Description>
        <PackageTags>Nexplore.Practices Practices CommandLine CLI</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.CommandLine" Version="2.0.11" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Nexplore.Practices.Core\Nexplore.Practices.Core.csproj" />
    </ItemGroup>

</Project>
